title: Stackbit Fresh Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: Akash Vijay Jujam
  tagline: Docs for Life!
  background: dark
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Projects
      url: /style-guide/
      style: link
    - label: Blog
      url: /blog/
      style: link
    - label: About
      url: /about/
      style: link
    - label: Contact
      url: /contact/
      style: link
  has_social: true
  social_links:
    - label: Instagram
      url: 'https://www.instagram.com/writerkash/'
      style: icon
      icon_class: instagram
      new_window: true
    - label: GitHub
      url: 'https://github.com/writerkash/Portfolio'
      style: icon
      icon_class: github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/akashjujam/'
      style: icon
      icon_class: linkedin
      new_window: true
    - label: Facebook
      url: 'https://www.facebook.com/jujamakash/'
      style: icon
      icon_class: facebook
      new_window: true
  profile_img: images/futuristic-lettuce.jpg
footer:
  content: >-
    &copy; 2021 Akash Jujam. All rights reserved.
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://scientific-europa-3590e.netlify.app'
